[package]
name = "tower_fighters"
version = "0.1.0"
authors = ["Pierre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"
ldtk_rust = "0.4.0"